# .github/workflows/build-and-test.yml
name: Build and Test

# This workflow runs on every push to any branch except 'main',
# and on every pull request that targets the 'main' or 'develop' branches.
on:
  push:
    branches:
      - '**' # All branches
      - '!main' # Exclude main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Specify your Go version

      - name: Install Dependencies
        run: go mod tidy

      - name: Run Linter
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Run Unit Tests with Coverage
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Generate HTML coverage report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.out
            coverage.html

      - name: Build Binary
        run: go build -v -o echos3 .
